### PR TITLE
W U No spell your package name correctly in install instructions ?

### PR DESCRIPTION
**Pull request by Carreau**
zsg9x

### CODE REVIEW

**Comment by rgbkrk** [comment]
Wow, we're awesome at typos over here. Thank you @Carreau!

**Comment by jdfreder** [comment]
Thanks!

**Comment by rgbkrk** [comment]
D'oh! You beat me to merging @jdfreder. Punishment for me waiting for CI on a doc update. :wink:

**Comment by captainsafia** [comment]
@rgbkrk — Now you know what it feels like.

@jdfreder with his darn quick fingers.

**Comment by jdfreder** [comment]
Video game reflexes :D

**Pull request merged**
